### ISSUE TITLE
[MRA] md5 issue

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/Arcade-MCR3Mono_MiSTer#1]
Hi,

I used the last version of mister (02/02/2020)
I have an issue of MD5 (mistmatch) for MAX RPM, Power Drive, Rampage and Sarge.
I tried to remove amd5="***" from MRA but the issue is still present.
Thanks.

**Comment by mrfpga** [comment]
I have sent a pull request that fixes this issue.

**Comment by wwark** [comment]
Thank you I closed this ticket.
