### ISSUE TITLE
[MRA] Demolition Derby issue

### ISSUE THREAD

**Issue by wwark** [MiSTer-devel/Arcade-MCR3Mono_MiSTer#7]
Hi,
Demolition derby not working with the merged rom.

Thanks

**Comment by sorgelig** [comment]
Do you get any error?
I use merged ROM 0216. It works.

**Comment by alanswx** [comment]
I fixed it for the non-merged rom.

**Comment by wwark** [comment]
Thank you for the fix. I need to check again the difference between merged and non-merged to have a correct title.
