### ISSUE TITLE
maxrpm MRA

### ISSUE THREAD

**Issue by eubrunosilva** [MiSTer-devel/Arcade-MCR3Mono_MiSTer#8]
Hi

you have

		<part crc="55c3b759" name="turbskwk.u4"/>
		<part crc="31a2da2e" name="turbskwk.u5"/>

but the correct crc for the files is:

		<part crc="31a2da2e" name="turbskwk.u4"/>
		<part crc="55c3b759" name="turbskwk.u5"/>

**Comment by sorgelig** [comment]
Thanks. Actually MiSTer doesn't use file names if CRC is present.
